// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package remote

import (
	"io"
	"sync"
)

// Ensure, that commandRunnerMock does implement commandRunner.
// If this is not the case, regenerate this file with moq.
var _ commandRunner = &commandRunnerMock{}

// commandRunnerMock is a mock implementation of commandRunner.
//
//	func TestSomethingThatUsescommandRunner(t *testing.T) {
//
//		// make and configure a mocked commandRunner
//		mockedcommandRunner := &commandRunnerMock{
//			RunFunc: func(name string, args []string, stdin io.Reader, stdout io.Writer, stderr io.Writer) error {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedcommandRunner in code that requires commandRunner
//		// and then make assertions.
//
//	}
type commandRunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(name string, args []string, stdin io.Reader, stdout io.Writer, stderr io.Writer) error

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
			// Stdin is the stdin argument value.
			Stdin io.Reader
			// Stdout is the stdout argument value.
			Stdout io.Writer
			// Stderr is the stderr argument value.
			Stderr io.Writer
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *commandRunnerMock) Run(name string, args []string, stdin io.Reader, stdout io.Writer, stderr io.Writer) error {
	if mock.RunFunc == nil {
		panic("commandRunnerMock.RunFunc: method is nil but commandRunner.Run was just called")
	}
	callInfo := struct {
		Name   string
		Args   []string
		Stdin  io.Reader
		Stdout io.Writer
		Stderr io.Writer
	}{
		Name:   name,
		Args:   args,
		Stdin:  stdin,
		Stdout: stdout,
		Stderr: stderr,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(name, args, stdin, stdout, stderr)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedcommandRunner.RunCalls())
func (mock *commandRunnerMock) RunCalls() []struct {
	Name   string
	Args   []string
	Stdin  io.Reader
	Stdout io.Writer
	Stderr io.Writer
} {
	var calls []struct {
		Name   string
		Args   []string
		Stdin  io.Reader
		Stdout io.Writer
		Stderr io.Writer
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
