// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package remote_test

import (
	"context"
	"sync"

	"github.com/TheOneWithTheWrench/go-fly/internal"
	"github.com/TheOneWithTheWrench/go-fly/internal/sources/remote"
)

// Ensure, that FetcherMock does implement remote.Fetcher.
// If this is not the case, regenerate this file with moq.
var _ remote.Fetcher = &FetcherMock{}

// FetcherMock is a mock implementation of remote.Fetcher.
//
//	func TestSomethingThatUsesFetcher(t *testing.T) {
//
//		// make and configure a mocked remote.Fetcher
//		mockedFetcher := &FetcherMock{
//			FetchAllFunc: func(contextMoqParam context.Context, refreshOutput internal.RefreshOutput) ([]internal.Repo, error) {
//				panic("mock out the FetchAll method")
//			},
//		}
//
//		// use mockedFetcher in code that requires remote.Fetcher
//		// and then make assertions.
//
//	}
type FetcherMock struct {
	// FetchAllFunc mocks the FetchAll method.
	FetchAllFunc func(contextMoqParam context.Context, refreshOutput internal.RefreshOutput) ([]internal.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchAll holds details about calls to the FetchAll method.
		FetchAll []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RefreshOutput is the refreshOutput argument value.
			RefreshOutput internal.RefreshOutput
		}
	}
	lockFetchAll sync.RWMutex
}

// FetchAll calls FetchAllFunc.
func (mock *FetcherMock) FetchAll(contextMoqParam context.Context, refreshOutput internal.RefreshOutput) ([]internal.Repo, error) {
	if mock.FetchAllFunc == nil {
		panic("FetcherMock.FetchAllFunc: method is nil but Fetcher.FetchAll was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		RefreshOutput   internal.RefreshOutput
	}{
		ContextMoqParam: contextMoqParam,
		RefreshOutput:   refreshOutput,
	}
	mock.lockFetchAll.Lock()
	mock.calls.FetchAll = append(mock.calls.FetchAll, callInfo)
	mock.lockFetchAll.Unlock()
	return mock.FetchAllFunc(contextMoqParam, refreshOutput)
}

// FetchAllCalls gets all the calls that were made to FetchAll.
// Check the length with:
//
//	len(mockedFetcher.FetchAllCalls())
func (mock *FetcherMock) FetchAllCalls() []struct {
	ContextMoqParam context.Context
	RefreshOutput   internal.RefreshOutput
} {
	var calls []struct {
		ContextMoqParam context.Context
		RefreshOutput   internal.RefreshOutput
	}
	mock.lockFetchAll.RLock()
	calls = mock.calls.FetchAll
	mock.lockFetchAll.RUnlock()
	return calls
}
