// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package internal_test

import (
	"context"
	"github.com/TheOneWithTheWrench/go-fly/internal"
	"sync"
)

// Ensure, that RemoteFetcherMock does implement internal.RemoteFetcher.
// If this is not the case, regenerate this file with moq.
var _ internal.RemoteFetcher = &RemoteFetcherMock{}

// RemoteFetcherMock is a mock implementation of internal.RemoteFetcher.
//
//	func TestSomethingThatUsesRemoteFetcher(t *testing.T) {
//
//		// make and configure a mocked internal.RemoteFetcher
//		mockedRemoteFetcher := &RemoteFetcherMock{
//			FetchAllFunc: func(contextMoqParam context.Context) ([]internal.Repo, error) {
//				panic("mock out the FetchAll method")
//			},
//		}
//
//		// use mockedRemoteFetcher in code that requires internal.RemoteFetcher
//		// and then make assertions.
//
//	}
type RemoteFetcherMock struct {
	// FetchAllFunc mocks the FetchAll method.
	FetchAllFunc func(contextMoqParam context.Context) ([]internal.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchAll holds details about calls to the FetchAll method.
		FetchAll []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockFetchAll sync.RWMutex
}

// FetchAll calls FetchAllFunc.
func (mock *RemoteFetcherMock) FetchAll(contextMoqParam context.Context) ([]internal.Repo, error) {
	if mock.FetchAllFunc == nil {
		panic("RemoteFetcherMock.FetchAllFunc: method is nil but RemoteFetcher.FetchAll was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockFetchAll.Lock()
	mock.calls.FetchAll = append(mock.calls.FetchAll, callInfo)
	mock.lockFetchAll.Unlock()
	return mock.FetchAllFunc(contextMoqParam)
}

// FetchAllCalls gets all the calls that were made to FetchAll.
// Check the length with:
//
//	len(mockedRemoteFetcher.FetchAllCalls())
func (mock *RemoteFetcherMock) FetchAllCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockFetchAll.RLock()
	calls = mock.calls.FetchAll
	mock.lockFetchAll.RUnlock()
	return calls
}

// Ensure, that PickerMock does implement internal.Picker.
// If this is not the case, regenerate this file with moq.
var _ internal.Picker = &PickerMock{}

// PickerMock is a mock implementation of internal.Picker.
//
//	func TestSomethingThatUsesPicker(t *testing.T) {
//
//		// make and configure a mocked internal.Picker
//		mockedPicker := &PickerMock{
//			PickFunc: func(s string, candidates []internal.Candidate) (internal.Candidate, bool, error) {
//				panic("mock out the Pick method")
//			},
//		}
//
//		// use mockedPicker in code that requires internal.Picker
//		// and then make assertions.
//
//	}
type PickerMock struct {
	// PickFunc mocks the Pick method.
	PickFunc func(s string, candidates []internal.Candidate) (internal.Candidate, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Pick holds details about calls to the Pick method.
		Pick []struct {
			// S is the s argument value.
			S string
			// Candidates is the candidates argument value.
			Candidates []internal.Candidate
		}
	}
	lockPick sync.RWMutex
}

// Pick calls PickFunc.
func (mock *PickerMock) Pick(s string, candidates []internal.Candidate) (internal.Candidate, bool, error) {
	if mock.PickFunc == nil {
		panic("PickerMock.PickFunc: method is nil but Picker.Pick was just called")
	}
	callInfo := struct {
		S          string
		Candidates []internal.Candidate
	}{
		S:          s,
		Candidates: candidates,
	}
	mock.lockPick.Lock()
	mock.calls.Pick = append(mock.calls.Pick, callInfo)
	mock.lockPick.Unlock()
	return mock.PickFunc(s, candidates)
}

// PickCalls gets all the calls that were made to Pick.
// Check the length with:
//
//	len(mockedPicker.PickCalls())
func (mock *PickerMock) PickCalls() []struct {
	S          string
	Candidates []internal.Candidate
} {
	var calls []struct {
		S          string
		Candidates []internal.Candidate
	}
	mock.lockPick.RLock()
	calls = mock.calls.Pick
	mock.lockPick.RUnlock()
	return calls
}

// Ensure, that RefresherMock does implement internal.Refresher.
// If this is not the case, regenerate this file with moq.
var _ internal.Refresher = &RefresherMock{}

// RefresherMock is a mock implementation of internal.Refresher.
//
//	func TestSomethingThatUsesRefresher(t *testing.T) {
//
//		// make and configure a mocked internal.Refresher
//		mockedRefresher := &RefresherMock{
//			LaunchFunc: func()  {
//				panic("mock out the Launch method")
//			},
//		}
//
//		// use mockedRefresher in code that requires internal.Refresher
//		// and then make assertions.
//
//	}
type RefresherMock struct {
	// LaunchFunc mocks the Launch method.
	LaunchFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Launch holds details about calls to the Launch method.
		Launch []struct {
		}
	}
	lockLaunch sync.RWMutex
}

// Launch calls LaunchFunc.
func (mock *RefresherMock) Launch() {
	if mock.LaunchFunc == nil {
		panic("RefresherMock.LaunchFunc: method is nil but Refresher.Launch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	mock.LaunchFunc()
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedRefresher.LaunchCalls())
func (mock *RefresherMock) LaunchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Ensure, that PrunerMock does implement internal.Pruner.
// If this is not the case, regenerate this file with moq.
var _ internal.Pruner = &PrunerMock{}

// PrunerMock is a mock implementation of internal.Pruner.
//
//	func TestSomethingThatUsesPruner(t *testing.T) {
//
//		// make and configure a mocked internal.Pruner
//		mockedPruner := &PrunerMock{
//			LaunchFunc: func()  {
//				panic("mock out the Launch method")
//			},
//		}
//
//		// use mockedPruner in code that requires internal.Pruner
//		// and then make assertions.
//
//	}
type PrunerMock struct {
	// LaunchFunc mocks the Launch method.
	LaunchFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Launch holds details about calls to the Launch method.
		Launch []struct {
		}
	}
	lockLaunch sync.RWMutex
}

// Launch calls LaunchFunc.
func (mock *PrunerMock) Launch() {
	if mock.LaunchFunc == nil {
		panic("PrunerMock.LaunchFunc: method is nil but Pruner.Launch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	mock.LaunchFunc()
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedPruner.LaunchCalls())
func (mock *PrunerMock) LaunchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Ensure, that ClonerMock does implement internal.Cloner.
// If this is not the case, regenerate this file with moq.
var _ internal.Cloner = &ClonerMock{}

// ClonerMock is a mock implementation of internal.Cloner.
//
//	func TestSomethingThatUsesCloner(t *testing.T) {
//
//		// make and configure a mocked internal.Cloner
//		mockedCloner := &ClonerMock{
//			CloneFunc: func(repo internal.Repo) (string, error) {
//				panic("mock out the Clone method")
//			},
//		}
//
//		// use mockedCloner in code that requires internal.Cloner
//		// and then make assertions.
//
//	}
type ClonerMock struct {
	// CloneFunc mocks the Clone method.
	CloneFunc func(repo internal.Repo) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Repo is the repo argument value.
			Repo internal.Repo
		}
	}
	lockClone sync.RWMutex
}

// Clone calls CloneFunc.
func (mock *ClonerMock) Clone(repo internal.Repo) (string, error) {
	if mock.CloneFunc == nil {
		panic("ClonerMock.CloneFunc: method is nil but Cloner.Clone was just called")
	}
	callInfo := struct {
		Repo internal.Repo
	}{
		Repo: repo,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(repo)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedCloner.CloneCalls())
func (mock *ClonerMock) CloneCalls() []struct {
	Repo internal.Repo
} {
	var calls []struct {
		Repo internal.Repo
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// Ensure, that RunnerMock does implement internal.Runner.
// If this is not the case, regenerate this file with moq.
var _ internal.Runner = &RunnerMock{}

// RunnerMock is a mock implementation of internal.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked internal.Runner
//		mockedRunner := &RunnerMock{
//			RunFunc: func(ctx context.Context, name string, args ...string) ([]byte, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires internal.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, name string, args ...string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Args []string
	}{
		Ctx:  ctx,
		Name: name,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx  context.Context
	Name string
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}

// Ensure, that SourceMock does implement internal.Source.
// If this is not the case, regenerate this file with moq.
var _ internal.Source = &SourceMock{}

// SourceMock is a mock implementation of internal.Source.
//
//	func TestSomethingThatUsesSource(t *testing.T) {
//
//		// make and configure a mocked internal.Source
//		mockedSource := &SourceMock{
//			LoadFunc: func(query string) ([]internal.Candidate, error) {
//				panic("mock out the Load method")
//			},
//		}
//
//		// use mockedSource in code that requires internal.Source
//		// and then make assertions.
//
//	}
type SourceMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func(query string) ([]internal.Candidate, error)

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
			// Query is the query argument value.
			Query string
		}
	}
	lockLoad sync.RWMutex
}

// Load calls LoadFunc.
func (mock *SourceMock) Load(query string) ([]internal.Candidate, error) {
	if mock.LoadFunc == nil {
		panic("SourceMock.LoadFunc: method is nil but Source.Load was just called")
	}
	callInfo := struct {
		Query string
	}{
		Query: query,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(query)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedSource.LoadCalls())
func (mock *SourceMock) LoadCalls() []struct {
	Query string
} {
	var calls []struct {
		Query string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Ensure, that RefreshableMock does implement internal.Refreshable.
// If this is not the case, regenerate this file with moq.
var _ internal.Refreshable = &RefreshableMock{}

// RefreshableMock is a mock implementation of internal.Refreshable.
//
//	func TestSomethingThatUsesRefreshable(t *testing.T) {
//
//		// make and configure a mocked internal.Refreshable
//		mockedRefreshable := &RefreshableMock{
//			RefreshFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedRefreshable in code that requires internal.Refreshable
//		// and then make assertions.
//
//	}
type RefreshableMock struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(contextMoqParam context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *RefreshableMock) Refresh(contextMoqParam context.Context) error {
	if mock.RefreshFunc == nil {
		panic("RefreshableMock.RefreshFunc: method is nil but Refreshable.Refresh was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(contextMoqParam)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedRefreshable.RefreshCalls())
func (mock *RefreshableMock) RefreshCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Ensure, that TrackableMock does implement internal.Trackable.
// If this is not the case, regenerate this file with moq.
var _ internal.Trackable = &TrackableMock{}

// TrackableMock is a mock implementation of internal.Trackable.
//
//	func TestSomethingThatUsesTrackable(t *testing.T) {
//
//		// make and configure a mocked internal.Trackable
//		mockedTrackable := &TrackableMock{
//			TrackFunc: func(s string) error {
//				panic("mock out the Track method")
//			},
//		}
//
//		// use mockedTrackable in code that requires internal.Trackable
//		// and then make assertions.
//
//	}
type TrackableMock struct {
	// TrackFunc mocks the Track method.
	TrackFunc func(s string) error

	// calls tracks calls to the methods.
	calls struct {
		// Track holds details about calls to the Track method.
		Track []struct {
			// S is the s argument value.
			S string
		}
	}
	lockTrack sync.RWMutex
}

// Track calls TrackFunc.
func (mock *TrackableMock) Track(s string) error {
	if mock.TrackFunc == nil {
		panic("TrackableMock.TrackFunc: method is nil but Trackable.Track was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockTrack.Lock()
	mock.calls.Track = append(mock.calls.Track, callInfo)
	mock.lockTrack.Unlock()
	return mock.TrackFunc(s)
}

// TrackCalls gets all the calls that were made to Track.
// Check the length with:
//
//	len(mockedTrackable.TrackCalls())
func (mock *TrackableMock) TrackCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockTrack.RLock()
	calls = mock.calls.Track
	mock.lockTrack.RUnlock()
	return calls
}

// Ensure, that PrunableMock does implement internal.Prunable.
// If this is not the case, regenerate this file with moq.
var _ internal.Prunable = &PrunableMock{}

// PrunableMock is a mock implementation of internal.Prunable.
//
//	func TestSomethingThatUsesPrunable(t *testing.T) {
//
//		// make and configure a mocked internal.Prunable
//		mockedPrunable := &PrunableMock{
//			PruneFunc: func() error {
//				panic("mock out the Prune method")
//			},
//		}
//
//		// use mockedPrunable in code that requires internal.Prunable
//		// and then make assertions.
//
//	}
type PrunableMock struct {
	// PruneFunc mocks the Prune method.
	PruneFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Prune holds details about calls to the Prune method.
		Prune []struct {
		}
	}
	lockPrune sync.RWMutex
}

// Prune calls PruneFunc.
func (mock *PrunableMock) Prune() error {
	if mock.PruneFunc == nil {
		panic("PrunableMock.PruneFunc: method is nil but Prunable.Prune was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPrune.Lock()
	mock.calls.Prune = append(mock.calls.Prune, callInfo)
	mock.lockPrune.Unlock()
	return mock.PruneFunc()
}

// PruneCalls gets all the calls that were made to Prune.
// Check the length with:
//
//	len(mockedPrunable.PruneCalls())
func (mock *PrunableMock) PruneCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPrune.RLock()
	calls = mock.calls.Prune
	mock.lockPrune.RUnlock()
	return calls
}

// Ensure, that LocalCleanerMock does implement internal.LocalCleaner.
// If this is not the case, regenerate this file with moq.
var _ internal.LocalCleaner = &LocalCleanerMock{}

// LocalCleanerMock is a mock implementation of internal.LocalCleaner.
//
//	func TestSomethingThatUsesLocalCleaner(t *testing.T) {
//
//		// make and configure a mocked internal.LocalCleaner
//		mockedLocalCleaner := &LocalCleanerMock{
//			RemoveFunc: func(s string) error {
//				panic("mock out the Remove method")
//			},
//		}
//
//		// use mockedLocalCleaner in code that requires internal.LocalCleaner
//		// and then make assertions.
//
//	}
type LocalCleanerMock struct {
	// RemoveFunc mocks the Remove method.
	RemoveFunc func(s string) error

	// calls tracks calls to the methods.
	calls struct {
		// Remove holds details about calls to the Remove method.
		Remove []struct {
			// S is the s argument value.
			S string
		}
	}
	lockRemove sync.RWMutex
}

// Remove calls RemoveFunc.
func (mock *LocalCleanerMock) Remove(s string) error {
	if mock.RemoveFunc == nil {
		panic("LocalCleanerMock.RemoveFunc: method is nil but LocalCleaner.Remove was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockRemove.Lock()
	mock.calls.Remove = append(mock.calls.Remove, callInfo)
	mock.lockRemove.Unlock()
	return mock.RemoveFunc(s)
}

// RemoveCalls gets all the calls that were made to Remove.
// Check the length with:
//
//	len(mockedLocalCleaner.RemoveCalls())
func (mock *LocalCleanerMock) RemoveCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockRemove.RLock()
	calls = mock.calls.Remove
	mock.lockRemove.RUnlock()
	return calls
}
