// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package internal_test

import (
	"context"
	"sync"

	"github.com/TheOneWithTheWrench/go-fly/internal"
)

// Ensure, that PickerMock does implement internal.Picker.
// If this is not the case, regenerate this file with moq.
var _ internal.Picker = &PickerMock{}

// PickerMock is a mock implementation of internal.Picker.
//
//	func TestSomethingThatUsesPicker(t *testing.T) {
//
//		// make and configure a mocked internal.Picker
//		mockedPicker := &PickerMock{
//			PickFunc: func(s string, candidates []internal.Candidate) (int, bool, error) {
//				panic("mock out the Pick method")
//			},
//		}
//
//		// use mockedPicker in code that requires internal.Picker
//		// and then make assertions.
//
//	}
type PickerMock struct {
	// PickFunc mocks the Pick method.
	PickFunc func(s string, candidates []internal.Candidate) (int, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Pick holds details about calls to the Pick method.
		Pick []struct {
			// S is the s argument value.
			S string
			// Candidates is the candidates argument value.
			Candidates []internal.Candidate
		}
	}
	lockPick sync.RWMutex
}

// Pick calls PickFunc.
func (mock *PickerMock) Pick(s string, candidates []internal.Candidate) (int, bool, error) {
	if mock.PickFunc == nil {
		panic("PickerMock.PickFunc: method is nil but Picker.Pick was just called")
	}
	callInfo := struct {
		S          string
		Candidates []internal.Candidate
	}{
		S:          s,
		Candidates: candidates,
	}
	mock.lockPick.Lock()
	mock.calls.Pick = append(mock.calls.Pick, callInfo)
	mock.lockPick.Unlock()
	return mock.PickFunc(s, candidates)
}

// PickCalls gets all the calls that were made to Pick.
// Check the length with:
//
//	len(mockedPicker.PickCalls())
func (mock *PickerMock) PickCalls() []struct {
	S          string
	Candidates []internal.Candidate
} {
	var calls []struct {
		S          string
		Candidates []internal.Candidate
	}
	mock.lockPick.RLock()
	calls = mock.calls.Pick
	mock.lockPick.RUnlock()
	return calls
}

// Ensure, that RefresherMock does implement internal.Refresher.
// If this is not the case, regenerate this file with moq.
var _ internal.Refresher = &RefresherMock{}

// RefresherMock is a mock implementation of internal.Refresher.
//
//	func TestSomethingThatUsesRefresher(t *testing.T) {
//
//		// make and configure a mocked internal.Refresher
//		mockedRefresher := &RefresherMock{
//			LaunchFunc: func()  {
//				panic("mock out the Launch method")
//			},
//		}
//
//		// use mockedRefresher in code that requires internal.Refresher
//		// and then make assertions.
//
//	}
type RefresherMock struct {
	// LaunchFunc mocks the Launch method.
	LaunchFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Launch holds details about calls to the Launch method.
		Launch []struct {
		}
	}
	lockLaunch sync.RWMutex
}

// Launch calls LaunchFunc.
func (mock *RefresherMock) Launch() {
	if mock.LaunchFunc == nil {
		panic("RefresherMock.LaunchFunc: method is nil but Refresher.Launch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	mock.LaunchFunc()
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedRefresher.LaunchCalls())
func (mock *RefresherMock) LaunchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Ensure, that PrunerMock does implement internal.Pruner.
// If this is not the case, regenerate this file with moq.
var _ internal.Pruner = &PrunerMock{}

// PrunerMock is a mock implementation of internal.Pruner.
//
//	func TestSomethingThatUsesPruner(t *testing.T) {
//
//		// make and configure a mocked internal.Pruner
//		mockedPruner := &PrunerMock{
//			LaunchFunc: func()  {
//				panic("mock out the Launch method")
//			},
//		}
//
//		// use mockedPruner in code that requires internal.Pruner
//		// and then make assertions.
//
//	}
type PrunerMock struct {
	// LaunchFunc mocks the Launch method.
	LaunchFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Launch holds details about calls to the Launch method.
		Launch []struct {
		}
	}
	lockLaunch sync.RWMutex
}

// Launch calls LaunchFunc.
func (mock *PrunerMock) Launch() {
	if mock.LaunchFunc == nil {
		panic("PrunerMock.LaunchFunc: method is nil but Pruner.Launch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	mock.LaunchFunc()
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedPruner.LaunchCalls())
func (mock *PrunerMock) LaunchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Ensure, that ClonerMock does implement internal.Cloner.
// If this is not the case, regenerate this file with moq.
var _ internal.Cloner = &ClonerMock{}

// ClonerMock is a mock implementation of internal.Cloner.
//
//	func TestSomethingThatUsesCloner(t *testing.T) {
//
//		// make and configure a mocked internal.Cloner
//		mockedCloner := &ClonerMock{
//			CloneFunc: func(repo internal.Repo) (string, error) {
//				panic("mock out the Clone method")
//			},
//		}
//
//		// use mockedCloner in code that requires internal.Cloner
//		// and then make assertions.
//
//	}
type ClonerMock struct {
	// CloneFunc mocks the Clone method.
	CloneFunc func(repo internal.Repo) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Repo is the repo argument value.
			Repo internal.Repo
		}
	}
	lockClone sync.RWMutex
}

// Clone calls CloneFunc.
func (mock *ClonerMock) Clone(repo internal.Repo) (string, error) {
	if mock.CloneFunc == nil {
		panic("ClonerMock.CloneFunc: method is nil but Cloner.Clone was just called")
	}
	callInfo := struct {
		Repo internal.Repo
	}{
		Repo: repo,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(repo)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedCloner.CloneCalls())
func (mock *ClonerMock) CloneCalls() []struct {
	Repo internal.Repo
} {
	var calls []struct {
		Repo internal.Repo
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// Ensure, that SourceMock does implement internal.Source.
// If this is not the case, regenerate this file with moq.
var _ internal.Source = &SourceMock{}

// SourceMock is a mock implementation of internal.Source.
//
//	func TestSomethingThatUsesSource(t *testing.T) {
//
//		// make and configure a mocked internal.Source
//		mockedSource := &SourceMock{
//			LoadFunc: func(contextMoqParam context.Context, s string) ([]internal.Candidate, error) {
//				panic("mock out the Load method")
//			},
//			ResolveFunc: func(candidate internal.Candidate) (string, error) {
//				panic("mock out the Resolve method")
//			},
//		}
//
//		// use mockedSource in code that requires internal.Source
//		// and then make assertions.
//
//	}
type SourceMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func(contextMoqParam context.Context, s string) ([]internal.Candidate, error)

	// ResolveFunc mocks the Resolve method.
	ResolveFunc func(candidate internal.Candidate) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// Resolve holds details about calls to the Resolve method.
		Resolve []struct {
			// Candidate is the candidate argument value.
			Candidate internal.Candidate
		}
	}
	lockLoad    sync.RWMutex
	lockResolve sync.RWMutex
}

// Load calls LoadFunc.
func (mock *SourceMock) Load(contextMoqParam context.Context, s string) ([]internal.Candidate, error) {
	if mock.LoadFunc == nil {
		panic("SourceMock.LoadFunc: method is nil but Source.Load was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(contextMoqParam, s)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedSource.LoadCalls())
func (mock *SourceMock) LoadCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Resolve calls ResolveFunc.
func (mock *SourceMock) Resolve(candidate internal.Candidate) (string, error) {
	if mock.ResolveFunc == nil {
		panic("SourceMock.ResolveFunc: method is nil but Source.Resolve was just called")
	}
	callInfo := struct {
		Candidate internal.Candidate
	}{
		Candidate: candidate,
	}
	mock.lockResolve.Lock()
	mock.calls.Resolve = append(mock.calls.Resolve, callInfo)
	mock.lockResolve.Unlock()
	return mock.ResolveFunc(candidate)
}

// ResolveCalls gets all the calls that were made to Resolve.
// Check the length with:
//
//	len(mockedSource.ResolveCalls())
func (mock *SourceMock) ResolveCalls() []struct {
	Candidate internal.Candidate
} {
	var calls []struct {
		Candidate internal.Candidate
	}
	mock.lockResolve.RLock()
	calls = mock.calls.Resolve
	mock.lockResolve.RUnlock()
	return calls
}

// Ensure, that RefreshableMock does implement internal.Refreshable.
// If this is not the case, regenerate this file with moq.
var _ internal.Refreshable = &RefreshableMock{}

// RefreshableMock is a mock implementation of internal.Refreshable.
//
//	func TestSomethingThatUsesRefreshable(t *testing.T) {
//
//		// make and configure a mocked internal.Refreshable
//		mockedRefreshable := &RefreshableMock{
//			RefreshFunc: func(contextMoqParam context.Context, refreshOutput internal.RefreshOutput) error {
//				panic("mock out the Refresh method")
//			},
//		}
//
//		// use mockedRefreshable in code that requires internal.Refreshable
//		// and then make assertions.
//
//	}
type RefreshableMock struct {
	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(contextMoqParam context.Context, refreshOutput internal.RefreshOutput) error

	// calls tracks calls to the methods.
	calls struct {
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// RefreshOutput is the refreshOutput argument value.
			RefreshOutput internal.RefreshOutput
		}
	}
	lockRefresh sync.RWMutex
}

// Refresh calls RefreshFunc.
func (mock *RefreshableMock) Refresh(contextMoqParam context.Context, refreshOutput internal.RefreshOutput) error {
	if mock.RefreshFunc == nil {
		panic("RefreshableMock.RefreshFunc: method is nil but Refreshable.Refresh was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		RefreshOutput   internal.RefreshOutput
	}{
		ContextMoqParam: contextMoqParam,
		RefreshOutput:   refreshOutput,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(contextMoqParam, refreshOutput)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedRefreshable.RefreshCalls())
func (mock *RefreshableMock) RefreshCalls() []struct {
	ContextMoqParam context.Context
	RefreshOutput   internal.RefreshOutput
} {
	var calls []struct {
		ContextMoqParam context.Context
		RefreshOutput   internal.RefreshOutput
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Ensure, that RefreshOutputMock does implement internal.RefreshOutput.
// If this is not the case, regenerate this file with moq.
var _ internal.RefreshOutput = &RefreshOutputMock{}

// RefreshOutputMock is a mock implementation of internal.RefreshOutput.
//
//	func TestSomethingThatUsesRefreshOutput(t *testing.T) {
//
//		// make and configure a mocked internal.RefreshOutput
//		mockedRefreshOutput := &RefreshOutputMock{
//			ClearStatusFunc: func() error {
//				panic("mock out the ClearStatus method")
//			},
//			SetStatusFunc: func(s string) error {
//				panic("mock out the SetStatus method")
//			},
//			WriteFunc: func(p []byte) (int, error) {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedRefreshOutput in code that requires internal.RefreshOutput
//		// and then make assertions.
//
//	}
type RefreshOutputMock struct {
	// ClearStatusFunc mocks the ClearStatus method.
	ClearStatusFunc func() error

	// SetStatusFunc mocks the SetStatus method.
	SetStatusFunc func(s string) error

	// WriteFunc mocks the Write method.
	WriteFunc func(p []byte) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// ClearStatus holds details about calls to the ClearStatus method.
		ClearStatus []struct {
		}
		// SetStatus holds details about calls to the SetStatus method.
		SetStatus []struct {
			// S is the s argument value.
			S string
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// P is the p argument value.
			P []byte
		}
	}
	lockClearStatus sync.RWMutex
	lockSetStatus   sync.RWMutex
	lockWrite       sync.RWMutex
}

// ClearStatus calls ClearStatusFunc.
func (mock *RefreshOutputMock) ClearStatus() error {
	if mock.ClearStatusFunc == nil {
		panic("RefreshOutputMock.ClearStatusFunc: method is nil but RefreshOutput.ClearStatus was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClearStatus.Lock()
	mock.calls.ClearStatus = append(mock.calls.ClearStatus, callInfo)
	mock.lockClearStatus.Unlock()
	return mock.ClearStatusFunc()
}

// ClearStatusCalls gets all the calls that were made to ClearStatus.
// Check the length with:
//
//	len(mockedRefreshOutput.ClearStatusCalls())
func (mock *RefreshOutputMock) ClearStatusCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClearStatus.RLock()
	calls = mock.calls.ClearStatus
	mock.lockClearStatus.RUnlock()
	return calls
}

// SetStatus calls SetStatusFunc.
func (mock *RefreshOutputMock) SetStatus(s string) error {
	if mock.SetStatusFunc == nil {
		panic("RefreshOutputMock.SetStatusFunc: method is nil but RefreshOutput.SetStatus was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockSetStatus.Lock()
	mock.calls.SetStatus = append(mock.calls.SetStatus, callInfo)
	mock.lockSetStatus.Unlock()
	return mock.SetStatusFunc(s)
}

// SetStatusCalls gets all the calls that were made to SetStatus.
// Check the length with:
//
//	len(mockedRefreshOutput.SetStatusCalls())
func (mock *RefreshOutputMock) SetStatusCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockSetStatus.RLock()
	calls = mock.calls.SetStatus
	mock.lockSetStatus.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *RefreshOutputMock) Write(p []byte) (int, error) {
	if mock.WriteFunc == nil {
		panic("RefreshOutputMock.WriteFunc: method is nil but RefreshOutput.Write was just called")
	}
	callInfo := struct {
		P []byte
	}{
		P: p,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(p)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedRefreshOutput.WriteCalls())
func (mock *RefreshOutputMock) WriteCalls() []struct {
	P []byte
} {
	var calls []struct {
		P []byte
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}

// Ensure, that TrackableMock does implement internal.Trackable.
// If this is not the case, regenerate this file with moq.
var _ internal.Trackable = &TrackableMock{}

// TrackableMock is a mock implementation of internal.Trackable.
//
//	func TestSomethingThatUsesTrackable(t *testing.T) {
//
//		// make and configure a mocked internal.Trackable
//		mockedTrackable := &TrackableMock{
//			TrackFunc: func(s string) error {
//				panic("mock out the Track method")
//			},
//		}
//
//		// use mockedTrackable in code that requires internal.Trackable
//		// and then make assertions.
//
//	}
type TrackableMock struct {
	// TrackFunc mocks the Track method.
	TrackFunc func(s string) error

	// calls tracks calls to the methods.
	calls struct {
		// Track holds details about calls to the Track method.
		Track []struct {
			// S is the s argument value.
			S string
		}
	}
	lockTrack sync.RWMutex
}

// Track calls TrackFunc.
func (mock *TrackableMock) Track(s string) error {
	if mock.TrackFunc == nil {
		panic("TrackableMock.TrackFunc: method is nil but Trackable.Track was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockTrack.Lock()
	mock.calls.Track = append(mock.calls.Track, callInfo)
	mock.lockTrack.Unlock()
	return mock.TrackFunc(s)
}

// TrackCalls gets all the calls that were made to Track.
// Check the length with:
//
//	len(mockedTrackable.TrackCalls())
func (mock *TrackableMock) TrackCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockTrack.RLock()
	calls = mock.calls.Track
	mock.lockTrack.RUnlock()
	return calls
}

// Ensure, that PrunableMock does implement internal.Prunable.
// If this is not the case, regenerate this file with moq.
var _ internal.Prunable = &PrunableMock{}

// PrunableMock is a mock implementation of internal.Prunable.
//
//	func TestSomethingThatUsesPrunable(t *testing.T) {
//
//		// make and configure a mocked internal.Prunable
//		mockedPrunable := &PrunableMock{
//			PruneFunc: func() error {
//				panic("mock out the Prune method")
//			},
//		}
//
//		// use mockedPrunable in code that requires internal.Prunable
//		// and then make assertions.
//
//	}
type PrunableMock struct {
	// PruneFunc mocks the Prune method.
	PruneFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Prune holds details about calls to the Prune method.
		Prune []struct {
		}
	}
	lockPrune sync.RWMutex
}

// Prune calls PruneFunc.
func (mock *PrunableMock) Prune() error {
	if mock.PruneFunc == nil {
		panic("PrunableMock.PruneFunc: method is nil but Prunable.Prune was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPrune.Lock()
	mock.calls.Prune = append(mock.calls.Prune, callInfo)
	mock.lockPrune.Unlock()
	return mock.PruneFunc()
}

// PruneCalls gets all the calls that were made to Prune.
// Check the length with:
//
//	len(mockedPrunable.PruneCalls())
func (mock *PrunableMock) PruneCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPrune.RLock()
	calls = mock.calls.Prune
	mock.lockPrune.RUnlock()
	return calls
}
