// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package internal_test

import (
	"context"
	"sync"

	"github.com/TheOneWithTheWrench/go-fly/internal"
)

// Ensure, that IndexStorageMock does implement internal.IndexStorage.
// If this is not the case, regenerate this file with moq.
var _ internal.IndexStorage = &IndexStorageMock{}

// IndexStorageMock is a mock implementation of internal.IndexStorage.
//
//	func TestSomethingThatUsesIndexStorage(t *testing.T) {
//
//		// make and configure a mocked internal.IndexStorage
//		mockedIndexStorage := &IndexStorageMock{
//			LoadFunc: func() ([]internal.Entry, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(entrys []internal.Entry) error {
//				panic("mock out the Save method")
//			},
//			UpsertFunc: func(entry internal.Entry) error {
//				panic("mock out the Upsert method")
//			},
//		}
//
//		// use mockedIndexStorage in code that requires internal.IndexStorage
//		// and then make assertions.
//
//	}
type IndexStorageMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() ([]internal.Entry, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(entrys []internal.Entry) error

	// UpsertFunc mocks the Upsert method.
	UpsertFunc func(entry internal.Entry) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Entrys is the entrys argument value.
			Entrys []internal.Entry
		}
		// Upsert holds details about calls to the Upsert method.
		Upsert []struct {
			// Entry is the entry argument value.
			Entry internal.Entry
		}
	}
	lockLoad   sync.RWMutex
	lockSave   sync.RWMutex
	lockUpsert sync.RWMutex
}

// Load calls LoadFunc.
func (mock *IndexStorageMock) Load() ([]internal.Entry, error) {
	if mock.LoadFunc == nil {
		panic("IndexStorageMock.LoadFunc: method is nil but IndexStorage.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedIndexStorage.LoadCalls())
func (mock *IndexStorageMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *IndexStorageMock) Save(entrys []internal.Entry) error {
	if mock.SaveFunc == nil {
		panic("IndexStorageMock.SaveFunc: method is nil but IndexStorage.Save was just called")
	}
	callInfo := struct {
		Entrys []internal.Entry
	}{
		Entrys: entrys,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(entrys)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedIndexStorage.SaveCalls())
func (mock *IndexStorageMock) SaveCalls() []struct {
	Entrys []internal.Entry
} {
	var calls []struct {
		Entrys []internal.Entry
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Upsert calls UpsertFunc.
func (mock *IndexStorageMock) Upsert(entry internal.Entry) error {
	if mock.UpsertFunc == nil {
		panic("IndexStorageMock.UpsertFunc: method is nil but IndexStorage.Upsert was just called")
	}
	callInfo := struct {
		Entry internal.Entry
	}{
		Entry: entry,
	}
	mock.lockUpsert.Lock()
	mock.calls.Upsert = append(mock.calls.Upsert, callInfo)
	mock.lockUpsert.Unlock()
	return mock.UpsertFunc(entry)
}

// UpsertCalls gets all the calls that were made to Upsert.
// Check the length with:
//
//	len(mockedIndexStorage.UpsertCalls())
func (mock *IndexStorageMock) UpsertCalls() []struct {
	Entry internal.Entry
} {
	var calls []struct {
		Entry internal.Entry
	}
	mock.lockUpsert.RLock()
	calls = mock.calls.Upsert
	mock.lockUpsert.RUnlock()
	return calls
}

// Ensure, that RemoteStorageMock does implement internal.RemoteStorage.
// If this is not the case, regenerate this file with moq.
var _ internal.RemoteStorage = &RemoteStorageMock{}

// RemoteStorageMock is a mock implementation of internal.RemoteStorage.
//
//	func TestSomethingThatUsesRemoteStorage(t *testing.T) {
//
//		// make and configure a mocked internal.RemoteStorage
//		mockedRemoteStorage := &RemoteStorageMock{
//			LoadFunc: func() (internal.Cache, bool, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(cache internal.Cache) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedRemoteStorage in code that requires internal.RemoteStorage
//		// and then make assertions.
//
//	}
type RemoteStorageMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (internal.Cache, bool, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(cache internal.Cache) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Cache is the cache argument value.
			Cache internal.Cache
		}
	}
	lockLoad sync.RWMutex
	lockSave sync.RWMutex
}

// Load calls LoadFunc.
func (mock *RemoteStorageMock) Load() (internal.Cache, bool, error) {
	if mock.LoadFunc == nil {
		panic("RemoteStorageMock.LoadFunc: method is nil but RemoteStorage.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedRemoteStorage.LoadCalls())
func (mock *RemoteStorageMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *RemoteStorageMock) Save(cache internal.Cache) error {
	if mock.SaveFunc == nil {
		panic("RemoteStorageMock.SaveFunc: method is nil but RemoteStorage.Save was just called")
	}
	callInfo := struct {
		Cache internal.Cache
	}{
		Cache: cache,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(cache)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedRemoteStorage.SaveCalls())
func (mock *RemoteStorageMock) SaveCalls() []struct {
	Cache internal.Cache
} {
	var calls []struct {
		Cache internal.Cache
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that RemoteFetcherMock does implement internal.RemoteFetcher.
// If this is not the case, regenerate this file with moq.
var _ internal.RemoteFetcher = &RemoteFetcherMock{}

// RemoteFetcherMock is a mock implementation of internal.RemoteFetcher.
//
//	func TestSomethingThatUsesRemoteFetcher(t *testing.T) {
//
//		// make and configure a mocked internal.RemoteFetcher
//		mockedRemoteFetcher := &RemoteFetcherMock{
//			FetchAllFunc: func(contextMoqParam context.Context) ([]internal.Repo, error) {
//				panic("mock out the FetchAll method")
//			},
//		}
//
//		// use mockedRemoteFetcher in code that requires internal.RemoteFetcher
//		// and then make assertions.
//
//	}
type RemoteFetcherMock struct {
	// FetchAllFunc mocks the FetchAll method.
	FetchAllFunc func(contextMoqParam context.Context) ([]internal.Repo, error)

	// calls tracks calls to the methods.
	calls struct {
		// FetchAll holds details about calls to the FetchAll method.
		FetchAll []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockFetchAll sync.RWMutex
}

// FetchAll calls FetchAllFunc.
func (mock *RemoteFetcherMock) FetchAll(contextMoqParam context.Context) ([]internal.Repo, error) {
	if mock.FetchAllFunc == nil {
		panic("RemoteFetcherMock.FetchAllFunc: method is nil but RemoteFetcher.FetchAll was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockFetchAll.Lock()
	mock.calls.FetchAll = append(mock.calls.FetchAll, callInfo)
	mock.lockFetchAll.Unlock()
	return mock.FetchAllFunc(contextMoqParam)
}

// FetchAllCalls gets all the calls that were made to FetchAll.
// Check the length with:
//
//	len(mockedRemoteFetcher.FetchAllCalls())
func (mock *RemoteFetcherMock) FetchAllCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockFetchAll.RLock()
	calls = mock.calls.FetchAll
	mock.lockFetchAll.RUnlock()
	return calls
}

// Ensure, that PickerMock does implement internal.Picker.
// If this is not the case, regenerate this file with moq.
var _ internal.Picker = &PickerMock{}

// PickerMock is a mock implementation of internal.Picker.
//
//	func TestSomethingThatUsesPicker(t *testing.T) {
//
//		// make and configure a mocked internal.Picker
//		mockedPicker := &PickerMock{
//			PickFunc: func(s string, candidates []internal.Candidate) (internal.Candidate, bool, error) {
//				panic("mock out the Pick method")
//			},
//		}
//
//		// use mockedPicker in code that requires internal.Picker
//		// and then make assertions.
//
//	}
type PickerMock struct {
	// PickFunc mocks the Pick method.
	PickFunc func(s string, candidates []internal.Candidate) (internal.Candidate, bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Pick holds details about calls to the Pick method.
		Pick []struct {
			// S is the s argument value.
			S string
			// Candidates is the candidates argument value.
			Candidates []internal.Candidate
		}
	}
	lockPick sync.RWMutex
}

// Pick calls PickFunc.
func (mock *PickerMock) Pick(s string, candidates []internal.Candidate) (internal.Candidate, bool, error) {
	if mock.PickFunc == nil {
		panic("PickerMock.PickFunc: method is nil but Picker.Pick was just called")
	}
	callInfo := struct {
		S          string
		Candidates []internal.Candidate
	}{
		S:          s,
		Candidates: candidates,
	}
	mock.lockPick.Lock()
	mock.calls.Pick = append(mock.calls.Pick, callInfo)
	mock.lockPick.Unlock()
	return mock.PickFunc(s, candidates)
}

// PickCalls gets all the calls that were made to Pick.
// Check the length with:
//
//	len(mockedPicker.PickCalls())
func (mock *PickerMock) PickCalls() []struct {
	S          string
	Candidates []internal.Candidate
} {
	var calls []struct {
		S          string
		Candidates []internal.Candidate
	}
	mock.lockPick.RLock()
	calls = mock.calls.Pick
	mock.lockPick.RUnlock()
	return calls
}

// Ensure, that RefreshLauncherMock does implement internal.RefreshLauncher.
// If this is not the case, regenerate this file with moq.
var _ internal.RefreshLauncher = &RefreshLauncherMock{}

// RefreshLauncherMock is a mock implementation of internal.RefreshLauncher.
//
//	func TestSomethingThatUsesRefreshLauncher(t *testing.T) {
//
//		// make and configure a mocked internal.RefreshLauncher
//		mockedRefreshLauncher := &RefreshLauncherMock{
//			LaunchFunc: func()  {
//				panic("mock out the Launch method")
//			},
//		}
//
//		// use mockedRefreshLauncher in code that requires internal.RefreshLauncher
//		// and then make assertions.
//
//	}
type RefreshLauncherMock struct {
	// LaunchFunc mocks the Launch method.
	LaunchFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Launch holds details about calls to the Launch method.
		Launch []struct {
		}
	}
	lockLaunch sync.RWMutex
}

// Launch calls LaunchFunc.
func (mock *RefreshLauncherMock) Launch() {
	if mock.LaunchFunc == nil {
		panic("RefreshLauncherMock.LaunchFunc: method is nil but RefreshLauncher.Launch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	mock.LaunchFunc()
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedRefreshLauncher.LaunchCalls())
func (mock *RefreshLauncherMock) LaunchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Ensure, that PruneStateStorageMock does implement internal.PruneStateStorage.
// If this is not the case, regenerate this file with moq.
var _ internal.PruneStateStorage = &PruneStateStorageMock{}

// PruneStateStorageMock is a mock implementation of internal.PruneStateStorage.
//
//	func TestSomethingThatUsesPruneStateStorage(t *testing.T) {
//
//		// make and configure a mocked internal.PruneStateStorage
//		mockedPruneStateStorage := &PruneStateStorageMock{
//			LoadFunc: func() (internal.PruneState, bool, error) {
//				panic("mock out the Load method")
//			},
//			SaveFunc: func(pruneState internal.PruneState) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedPruneStateStorage in code that requires internal.PruneStateStorage
//		// and then make assertions.
//
//	}
type PruneStateStorageMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func() (internal.PruneState, bool, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(pruneState internal.PruneState) error

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// PruneState is the pruneState argument value.
			PruneState internal.PruneState
		}
	}
	lockLoad sync.RWMutex
	lockSave sync.RWMutex
}

// Load calls LoadFunc.
func (mock *PruneStateStorageMock) Load() (internal.PruneState, bool, error) {
	if mock.LoadFunc == nil {
		panic("PruneStateStorageMock.LoadFunc: method is nil but PruneStateStorage.Load was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc()
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedPruneStateStorage.LoadCalls())
func (mock *PruneStateStorageMock) LoadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *PruneStateStorageMock) Save(pruneState internal.PruneState) error {
	if mock.SaveFunc == nil {
		panic("PruneStateStorageMock.SaveFunc: method is nil but PruneStateStorage.Save was just called")
	}
	callInfo := struct {
		PruneState internal.PruneState
	}{
		PruneState: pruneState,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(pruneState)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedPruneStateStorage.SaveCalls())
func (mock *PruneStateStorageMock) SaveCalls() []struct {
	PruneState internal.PruneState
} {
	var calls []struct {
		PruneState internal.PruneState
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that PruneLauncherMock does implement internal.PruneLauncher.
// If this is not the case, regenerate this file with moq.
var _ internal.PruneLauncher = &PruneLauncherMock{}

// PruneLauncherMock is a mock implementation of internal.PruneLauncher.
//
//	func TestSomethingThatUsesPruneLauncher(t *testing.T) {
//
//		// make and configure a mocked internal.PruneLauncher
//		mockedPruneLauncher := &PruneLauncherMock{
//			LaunchFunc: func()  {
//				panic("mock out the Launch method")
//			},
//		}
//
//		// use mockedPruneLauncher in code that requires internal.PruneLauncher
//		// and then make assertions.
//
//	}
type PruneLauncherMock struct {
	// LaunchFunc mocks the Launch method.
	LaunchFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Launch holds details about calls to the Launch method.
		Launch []struct {
		}
	}
	lockLaunch sync.RWMutex
}

// Launch calls LaunchFunc.
func (mock *PruneLauncherMock) Launch() {
	if mock.LaunchFunc == nil {
		panic("PruneLauncherMock.LaunchFunc: method is nil but PruneLauncher.Launch was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLaunch.Lock()
	mock.calls.Launch = append(mock.calls.Launch, callInfo)
	mock.lockLaunch.Unlock()
	mock.LaunchFunc()
}

// LaunchCalls gets all the calls that were made to Launch.
// Check the length with:
//
//	len(mockedPruneLauncher.LaunchCalls())
func (mock *PruneLauncherMock) LaunchCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLaunch.RLock()
	calls = mock.calls.Launch
	mock.lockLaunch.RUnlock()
	return calls
}

// Ensure, that ClonerMock does implement internal.Cloner.
// If this is not the case, regenerate this file with moq.
var _ internal.Cloner = &ClonerMock{}

// ClonerMock is a mock implementation of internal.Cloner.
//
//	func TestSomethingThatUsesCloner(t *testing.T) {
//
//		// make and configure a mocked internal.Cloner
//		mockedCloner := &ClonerMock{
//			CloneFunc: func(repo internal.Repo) (string, error) {
//				panic("mock out the Clone method")
//			},
//		}
//
//		// use mockedCloner in code that requires internal.Cloner
//		// and then make assertions.
//
//	}
type ClonerMock struct {
	// CloneFunc mocks the Clone method.
	CloneFunc func(repo internal.Repo) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Clone holds details about calls to the Clone method.
		Clone []struct {
			// Repo is the repo argument value.
			Repo internal.Repo
		}
	}
	lockClone sync.RWMutex
}

// Clone calls CloneFunc.
func (mock *ClonerMock) Clone(repo internal.Repo) (string, error) {
	if mock.CloneFunc == nil {
		panic("ClonerMock.CloneFunc: method is nil but Cloner.Clone was just called")
	}
	callInfo := struct {
		Repo internal.Repo
	}{
		Repo: repo,
	}
	mock.lockClone.Lock()
	mock.calls.Clone = append(mock.calls.Clone, callInfo)
	mock.lockClone.Unlock()
	return mock.CloneFunc(repo)
}

// CloneCalls gets all the calls that were made to Clone.
// Check the length with:
//
//	len(mockedCloner.CloneCalls())
func (mock *ClonerMock) CloneCalls() []struct {
	Repo internal.Repo
} {
	var calls []struct {
		Repo internal.Repo
	}
	mock.lockClone.RLock()
	calls = mock.calls.Clone
	mock.lockClone.RUnlock()
	return calls
}

// Ensure, that RunnerMock does implement internal.Runner.
// If this is not the case, regenerate this file with moq.
var _ internal.Runner = &RunnerMock{}

// RunnerMock is a mock implementation of internal.Runner.
//
//	func TestSomethingThatUsesRunner(t *testing.T) {
//
//		// make and configure a mocked internal.Runner
//		mockedRunner := &RunnerMock{
//			RunFunc: func(ctx context.Context, name string, args ...string) ([]byte, error) {
//				panic("mock out the Run method")
//			},
//		}
//
//		// use mockedRunner in code that requires internal.Runner
//		// and then make assertions.
//
//	}
type RunnerMock struct {
	// RunFunc mocks the Run method.
	RunFunc func(ctx context.Context, name string, args ...string) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Run holds details about calls to the Run method.
		Run []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Args is the args argument value.
			Args []string
		}
	}
	lockRun sync.RWMutex
}

// Run calls RunFunc.
func (mock *RunnerMock) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	if mock.RunFunc == nil {
		panic("RunnerMock.RunFunc: method is nil but Runner.Run was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
		Args []string
	}{
		Ctx:  ctx,
		Name: name,
		Args: args,
	}
	mock.lockRun.Lock()
	mock.calls.Run = append(mock.calls.Run, callInfo)
	mock.lockRun.Unlock()
	return mock.RunFunc(ctx, name, args...)
}

// RunCalls gets all the calls that were made to Run.
// Check the length with:
//
//	len(mockedRunner.RunCalls())
func (mock *RunnerMock) RunCalls() []struct {
	Ctx  context.Context
	Name string
	Args []string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
		Args []string
	}
	mock.lockRun.RLock()
	calls = mock.calls.Run
	mock.lockRun.RUnlock()
	return calls
}
