// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package zoxide_test

import (
	"context"
	"github.com/TheOneWithTheWrench/go-fly/internal/sources/zoxide"
	"sync"
)

// Ensure, that ListerMock does implement zoxide.Lister.
// If this is not the case, regenerate this file with moq.
var _ zoxide.Lister = &ListerMock{}

// ListerMock is a mock implementation of zoxide.Lister.
//
//	func TestSomethingThatUsesLister(t *testing.T) {
//
//		// make and configure a mocked zoxide.Lister
//		mockedLister := &ListerMock{
//			ListFunc: func(contextMoqParam context.Context) ([]zoxide.Match, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedLister in code that requires zoxide.Lister
//		// and then make assertions.
//
//	}
type ListerMock struct {
	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context) ([]zoxide.Match, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockList sync.RWMutex
}

// List calls ListFunc.
func (mock *ListerMock) List(contextMoqParam context.Context) ([]zoxide.Match, error) {
	if mock.ListFunc == nil {
		panic("ListerMock.ListFunc: method is nil but Lister.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedLister.ListCalls())
func (mock *ListerMock) ListCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
